[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.2.3"

[[constraint]]
  name = "github.com/unidoc/unidoc"
  version = "2.0.1"

[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "v1.0.3"

[[constraint]]
  name = "github.com/xlab/closer"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "v0.0.1"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "v1.0.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"
